The purpose of this assignment is to start performing numeric data analysis using Python and the NumPy module, using real world data.

Skills:
In order to complete this assignment you will need to:

Import and manipulate the data into a workable form
Utilize Numpy functionalities to answer analytical questions
Practice python fundamentals and best practices
Knowledge:
This assignment will help you gain the following:

Load data into Numpy ndarrays
Perform data manipulation using ndarrays

Instructions:

In [81]:
""" 1. Data collection and analysis have revolutionized modern sports, especially basketball. Analysts, teams, coaches, and players all participate with the hope that the insights it provides will give them a competitive edge. Common analyses include player performance analysis, opponent scouting, game strategy optimization, injury prevention, fan engagement, and player recruitment. Use the data provided, a subset of the data contained in a Kaggle RepositoryLinks to an external site., to answer the following questions."""

' 1. Data collection and analysis have revolutionized modern sports, especially basketball. Analysts, teams, coaches, and players all participate with the hope that the insights it provides will give them a competitive edge. Common analyses include player performance analysis, opponent scouting, game strategy optimization, injury prevention, fan engagement, and player recruitment. Use the data provided, a subset of the data contained in a Kaggle RepositoryLinks to an external site., to answer the following questions.'

In [82]:
import numpy as np

In [83]:
# Load the files
Player_stats = np.loadtxt("NBA_Player_Stats.tsv", delimiter='\t', dtype=str, skiprows=1)
player_col_names = np.loadtxt("NBA_Column_Names.txt", delimiter="\t", dtype=str)

# Identify the indices of the relevant columns
fgm_index = np.where(player_col_names == 'Field Goals Made')[0][0]
fga_index = np.where(player_col_names == 'Field Goals Attempted')[0][0]
tpm_index = np.where(player_col_names == 'Three Pointers Made')[0][0]
tpa_index = np.where(player_col_names == 'Three Pointers Attempted')[0][0]
ftm_index = np.where(player_col_names=="Free Throws Made")[0][0]
fta_index = np.where(player_col_names =="Free Throws Attempted")[0][0]

#Extract the relevant columns and convert them to numeric
fgm_column = Player_stats[:, fgm_index].astype(float)
tpm_column = Player_stats[:, tpm_index].astype(float)
fga_column = Player_stats[:, fga_index].astype(float)
tpa_column = Player_stats[:, tpa_index].astype(float)
ftm_column = Player_stats[:, ftm_index].astype(float)
fta_column = Player_stats[:, fta_index].astype(float)

#Calculate shooting percentages
# Avoid division by zero by using np.where to handle cases where attempts are zero
fgm_percentage = np.where(fga_column > 0, (fgm_column / fga_column) * 100, 0)
tpm_percentage = np.where(tpa_column > 0, (tpm_column / tpa_column) * 100, 0)
ftm_percentage = np.where(fta_column > 0, (ftm_column / fta_column) * 100, 0)
# Optional: Combine results into a single array for easier access
shooting_percentages = np.column_stack((fgm_percentage, tpm_percentage, ftm_percentage))

# Average the point for each player by the minutes played
min_index = np.where(player_col_names =="Minutes Played")[0][0]
min_column = Player_stats[:,min_index].astype(float)
min_score_average = np.where(min_column > 0, (fgm_column + tpm_column + ftm_column) / min_column, 0)

#overall shooting percentage 
overall_shootting_percentage = np.where((fga_column+tpa_column+fta_column) > 0, ((fgm_column+tpm_column+ftm_column) / (fga_column+tpa_column+fta_column)) * 100, 0)

#average number of blocks per game
blk_index = np.where(player_col_names == "Blocks")[0][0]
blk_column = Player_stats[:,blk_index].astype(float)
blk_average = np.where(min_column > 0 , blk_column / min_column, 0)
# average number of steals per game
stl_index = np.where(player_col_names == "Steals")[0][0]
stl_column = Player_stats[:,stl_index].astype(float)
stl_average = np.where(min_column > 0 , stl_column / min_column, 0)

#print("Field Goal Percentage:", fgm_percentage)
#print("Three Point Percentage:", tpm_percentage)
#print("Combined Shooting Percentages:\n", shooting_percentages)


C:\Users\yemer\AppData\Local\Temp\ipykernel_26004\3673016692.py:25: RuntimeWarning: invalid value encountered in divide
  fgm_percentage = np.where(fga_column > 0, (fgm_column / fga_column) * 100, 0)
C:\Users\yemer\AppData\Local\Temp\ipykernel_26004\3673016692.py:26: RuntimeWarning: invalid value encountered in divide
  tpm_percentage = np.where(tpa_column > 0, (tpm_column / tpa_column) * 100, 0)
C:\Users\yemer\AppData\Local\Temp\ipykernel_26004\3673016692.py:27: RuntimeWarning: invalid value encountered in divide
  ftm_percentage = np.where(fta_column > 0, (ftm_column / fta_column) * 100, 0)
C:\Users\yemer\AppData\Local\Temp\ipykernel_26004\3673016692.py:37: RuntimeWarning: invalid value encountered in divide
  overall_shootting_percentage = np.where((fga_column+tpa_column+fta_column) > 0, ((fgm_column+tpm_column+ftm_column) / (fga_column+tpa_column+fta_column)) * 100, 0)


In [84]:
#A. Determine the field goal accuracy, three point accuracy, and free throw accuracy for each player in each season.
#field goal accuracy 
print("Field Goal Percentage:", fgm_percentage)
print("Three Point Percentage:", tpm_percentage)
print("Free Throw Percentage:",ftm_percentage)
print("Combined Shooting Percentages:\n", shooting_percentages)

Field Goal Percentage: [57.41741742 46.46226415 50.94850949 ... 43.04635762 52.11267606
 29.06976744]
Three Point Percentage: [ 0.         40.25423729 25.         ... 23.72881356 42.85714286
 25.        ]
Free Throw Percentage: [52.42718447 79.12885662 79.70230041 ... 63.63636364 66.66666667
 65.51724138]
Combined Shooting Percentages:
 [[57.41741742  0.         52.42718447]
 [46.46226415 40.25423729 79.12885662]
 [50.94850949 25.         79.70230041]
 ...
 [43.04635762 23.72881356 63.63636364]
 [52.11267606 42.85714286 66.66666667]
 [29.06976744 25.         65.51724138]]


In [85]:
#B. Determine the averrage points scored per minute for each player in each season.
print("Average Points Scored per Minute:", min_score_average)

Average Points Scored per Minute: [0.4388239  0.42194498 0.45571768 ... 0.18689956 0.24953445 0.13943699]


In [86]:
#C. Determine the overall shooting accuracy of each player in each season.
print("Overall Shooting Percentage:", overall_shootting_percentage)

Overall Shooting Percentage: [55.74297189 53.12122433 60.41385515 ... 42.12598425 53.17460317
 35.09933775]


In [87]:
#D. Determine the average number of blocks per game and the average number of steals per game for each player in each season.
print("Average Blocks per Game:",blk_average)
print("Average Steals per Game:",stl_average)

Average Blocks per Game: [0.07556118 0.02943058 0.0240923  ... 0.02445415 0.04469274 0.02104709]
Average Steals per Game: [0.0113816  0.03518874 0.02680692 ... 0.02270742 0.04096834 0.04735596]


In [88]:
"""2. Create a list of the top 100 players and corresponding season for each of your calculated metrics: field goal accuracy, three point accuracy, free throw accuracy, average points scored per game, overall shooting accuracy, average blocks per game, and average steals per game. """

'2. Create a list of the top 100 players and corresponding season for each of your calculated metrics: field goal accuracy, three point accuracy, free throw accuracy, average points scored per game, overall shooting accuracy, average blocks per game, and average steals per game. '

In [89]:

# Get indices that would sort the array
# Indices that would sort the values
sorted_indices_field_goal_percentage = np.argsort(fgm_percentage)[::-1]
sorted_indices_three_point_percentage = np.argsort(tpm_percentage)[::-1]
sorted_indices_free_throw_percentage = np.argsort(ftm_percentage)[::-1]
sorted_indices_average_points_scored = np.argsort(min_score_average)[::-1]
sorted_indices_overall_shooting_percentage = np.argsort(overall_shootting_percentage)[::-1]
sorted_indices_average_blocks = np.argsort(blk_average)[::-1]
sorted_indices_average_steals = np.argsort(stl_average)[::-1]


# Get the top 100 indices for each metric
top_100_fgp_indices = sorted_indices_field_goal_percentage[:100]  # Field Goal Percentage
top_100_tpp_indices = sorted_indices_three_point_percentage[:100]  # Three Point Percentage
top_100_ftp_indices = sorted_indices_free_throw_percentage[:100]  # Free Throw Percentage
top_100_ppg_indices = sorted_indices_average_points_scored[:100]  # Average Points Scored
top_100_osp_indices = sorted_indices_overall_shooting_percentage[:100]  # Overall Shooting Percentage
top_100_bpg_indices = sorted_indices_average_blocks[:100]  # Average Blocks
top_100_spg_indices = sorted_indices_average_steals[:100]  # Average Steals


# Step 3: Combine all top 100 arrays into a structured array (7 columns)
# Combine all top 100 arrays into a structured array (7 columns)
top_hundred_players = np.column_stack((
    top_100_fgp_indices,  # Field Goal Percentage
    top_100_tpp_indices,  # Three Point Percentage
    top_100_ftp_indices,  # Free Throw Percentage
    top_100_ppg_indices,  # Average Points Scored
    top_100_osp_indices,  # Overall Shooting Percentage
    top_100_bpg_indices,  # Average Blocks
    top_100_spg_indices   # Average Steals
))

# Print the final structured array for the top 100 players
print("Top 100 Players Metrics:\n", top_hundred_players)

                                      
                                      

Top 100 Players Metrics:
 [[4535 4634 4567 4086 1164 2568 4377]
 [4552 1806 1870 4378 4581 1373 2398]
 [4371 2970   74 3520 4371 3379 4606]
 [3589  494 3040 4381 4535 2011 3270]
 [3186  562 2087 3808 2373 4297 1034]
 [3390 2801 2286 3522 3223  922 4629]
 [4297  767 1896 3324 4628  763 3167]
 [4437 2042 1075 4382 2539  341 2046]
 [2411 3502 2532 4383 4572 1544 3021]
 [4581  397 1125 3521 4634  567 2720]
 [4628  104 4446 1219 4437 2674 1636]
 [2539 3941 1671 3835 4217  996 1845]
 [3007 1432  232 4384 4297 3286 2952]
 [4568 1436  984 2906 1625 2801 3079]
 [4134 1860 4164 4097 2814 1403 2824]
 [4634 1404 2507 4379 3084 1830 1576]
 [3223 2110  807 4391 3573  193 3423]
 [4572 2657 4565 3120 4568   11 2466]
 [3573 2849 3008 4092 4134  586 2646]
 [3793 2623 1815 4093 4325  699 3820]
 [3070  865  506  590 3268 2810  648]
 [3984  171 1247 3323 4532 1744 1961]
 [2373  643 2009 3118 2314  125   29]
 [3868  500 1070 3529 1979 2008 2579]
 [3706 2639 3835 4415 4266  581  736]
 [3726 1831 1038 2051 14